"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "../components/NavBar";
import React, { createContext } from "react";
import { fetchUserData } from "./utils/fetchUserData";

const inter = Inter({ subsets: ["latin"] });

export const UserContext = createContext();

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [userData, setUserData] = React.useState(null);
  const [token, setToken] = React.useState(null);

  // Check if the token has changed
  if (typeof window !== "undefined") {
    const newToken = localStorage.getItem("token");
    if (newToken && newToken !== token) setToken(newToken);
  }

  // Fetch user data when the token changes
  React.useEffect(() => {
    async function asyncFetchUserData() {
      if (!token) return;
      const data = await fetchUserData(token);
      setUserData(data);
    }
    asyncFetchUserData();
  }, [token]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext.Provider value={{token, userData, setUserData }}>
          <NavBar />
          <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
            {children}
          </main>
        </UserContext.Provider>
      </body>
    </html>
  );
}
